networks:
  microservice-networks:
    driver: bridge


services:
  discoveryserver:
    build:
      context: .
      dockerfile: discoveryserver/Dockerfile
    image: "lductai98/discoveryserver:latest"
    ports:
      - "8761:8761"
    networks:
      - microservice-networks
