version: '3.8'

networks:
  microservice-networks:
    driver: bridge


services:
  discoveryserver:
    build:
      context: .
      dockerfile: discoveryserver/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservice-networks
