

spring:
  application:
    name: commonservice
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:default-group}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ronin52014@gmail.com
    password: pcos ggqy mfdb ycfb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
