

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:default-group}
  application:
    name: commonservice
  mail:
    host: smtp.gmail.com
    port: 587
    username: ronin52014@gmail.com
    properties:
      mail:
        smptp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
