
spring:
  application:
    name: bookservice
  datasource:
      url: jdbc:h2:mem:bookdb
      username: sa
      password: password
      driverClassName: org.h2.Driver
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
  h2:
      console:
        enabled: true
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

